#!/bin/sh

# SPDX-License-Identifier: BlueOak-1.0.0

# Ensure that Git is installed.
if ! which git >/dev/null 2>&1; then
  echo "Could not find Git on PATH." >/dev/stderr
  exit 1
fi

# Ensure that we're running in a Git repository.
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo "$PWD is not a Git repository." >/dev/stderr
  exit 1
fi

# Print every commit's author name and committer name,
# separated by a newline.
git log --pretty="%an%n%cn" | sort -u
